### ISSUE TITLE
Install script fails to detect OS - Linux

### ISSUE THREAD

**Issue by pingud98** [im-tomu/fomu-toolchain#7]
The installation bash script failed to detect my linux install - so I just put it in the * part at the end. Here's my uname -a output

Linux cb14 4.16.18-galliumos #1 SMP PREEMPT Sun Jun 23 04:14:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by xobs** [comment]
There is no "installation bash script".  The script at the root of the repository is `build.sh` which packages toolchains.  Packages for Linux are statically-linked, so since you're running 64-bit Linux you should download the linux_x86_64 release from [http://github.com/im-tomu/fomu-toolchain/releases/latest](http://github.com/im-tomu/fomu-toolchain/releases/latest).
